HIDDEN_SIZE = 256
MAX_SENTENCE_LEN = 160
EMBED_LEN = 300
EMBED_FILE = 'data/glove.42B.300d.txt' #  also change the EMBED_LEN when changing this
TRAIN_BATCH_SIZE = 256
VALIDATION_BATCH_SIZE = 400
TEST_BATCH_SIZE = 400
TRAIN_FILES = ['data/train.tfrecords']
VALIDATION_FILES = ['data/validation_v1.tfrecords']
TEST_FILES = ['data/test_v1.tfrecords']
NUM_EXAMPLES_TRAIN = 1000000
NUM_EXAMPLES_VALID = 195600
NUM_EXAMPLES_TEST = 189200
CHECKPOINT_PATH = 'checkpoints'
CHECKPOINT_FILE = 'checkpoints/model_{}_{}.ckpt'.format(0,5859)  # edit before running test
VOCABULARY = 'data/vocabulary.json'
